# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#conference-proceedings"
  weight = 20

[[main]]
  name = "Projects"
  url = "projects-landing/"
  weight = 30

[[main]]
  name = "Presentations"
  url = "presentations-landing/"
  weight = 40

[[main]]
  name = "Showcase"
  url = "showcase-landing/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
   name = "CV"
   url = "media/cv.pdf"
   weight = 70
